name: Build LaTeX document

on:
  push:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v4

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ./rendercv_output/*.pdf
          retention-days: 3
      # test timezone
      # Set the date time
      - name: Retrieve current Date Time in Singapore TimeZone
        shell: bash
        run: echo "START_TIME=$(TZ=":Europe/Paris" date -R|sed 's/.....$//')" >> $GITHUB_ENV
        
      - name: Get time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: 2
          format: 'YYYY.MM.DD.HH.mm.ss'

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@master
        with:
          name: '${{ env.START_TIME }}'
          files: ./rendercv_output/*.pdf
          body: |
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pellentesque erat in blandit luctus. 
            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices ${{ env.START_TIME }}

      - name: Install ghostscript
        run: sudo apt-get update --fix-missing && sudo apt install ghostscript
      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          
          HGT="name=${DQT}height${DQT} value=${DQT}10KP${DQT}"
          HGTR="name=${DQT}height${DQT} value=${DQT}128Kp${DQT}"
          
          WDT="name=${DQT}width${DQT} value=${DQT}10KP${DQT}"
          WDTR="name=${DQT}width${DQT} value=${DQT}128Kp${DQT}"
          
          MAP="name=${DQT}map${DQT} value=${DQT}512MiB${DQT}"
          MAPR="name=${DQT}map${DQT} value=${DQT}4GiB${DQT}"
          
          MEM="name=${DQT}memory${DQT} value=${DQT}256MiB${DQT}"
          MEMR="name=${DQT}memory${DQT} value=${DQT}2GiB${DQT}"
          
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$HGT/$HGTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$WDT/$WDTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MAP/$MAPR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MEM/$MEMR/" /etc/ImageMagick-6/policy.xml
          
      - name: Convert pdf to png
        run: convert -density 900 -alpha off ./rendercv_output/*.pdf -resize 25% -quality 70 cv_preview_%d.png
        
      - name: Commit png
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add *.png
          git commit -m "[bot] updated preview images."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # Fetch the date time as Github ENV variable
      - name: print date
        run: echo ${{ env.START_TIME }}
