name: Process and Update CV Files

on: [pull_request, push]

jobs:
  cv_processing:
    runs-on: ubuntu-latest
    needs: [set_env_variables_job, update_packages_job, modify_policy_and_convert_job, commit_png_files_job, create_github_release_job]

  set_env_variables_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "CHANGELOG=$(TZ=":Europe/Paris" date +'%A, %d %B %Y %T %Z')" >> $GITHUB_ENV
          echo "NAME=$(TZ=":Europe/Paris" date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
          echo "TAG=$(TZ=":Europe/Paris" date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

  update_packages_job:
    runs-on: ubuntu-latest
    needs: [set_env_variables_job]
    steps:
      - name: Update Packages
        run: sudo apt-get update --fix-missing && sudo apt install ghostscript

  modify_policy_and_convert_job:
    runs-on: ubuntu-latest
    needs: [update_packages_job]
    steps:
      - name: Modify ImageMagick Policy
        run: |
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/; s/name="height" value="10KP"/name="height" value="128Kp"/; s/name="width" value="10KP"/name="width" value="128Kp"/; s/name="map" value="512MiB"/name="map" value="4GiB"/; s/name="memory" value="256MiB"/name="memory" value="2GiB"/'
      - name: Convert PDF to PNG
        run: convert -density 900 -alpha off ./rendercv_output/*.pdf -resize 25% -quality 50 cv_preview_%d.png

  commit_png_files_job:
    runs-on: ubuntu-latest
    needs: [modify_policy_and_convert_job]
    steps:
      - name: Commit PNG Files
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add *.png
          git commit -m "docs(bot): updated preview images"

  create_github_release_job:
    runs-on: ubuntu-latest
    needs: [set_env_variables_job]
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          name: '${{ env.NAME }}'
          tag_name: '${{ env.TAG }}'
          files: ./rendercv_output/*.pdf
          body: |
            CV updated on **${{ env.CHANGELOG }}**.
            You can download the latest version by [clicking here](https://github.com/c2tz/cvv/releases/download/${{ env.NAME }}/Google_CV.pdf).

  update_readme_job:
    runs-on: ubuntu-latest
    needs: [commit_png_files_job, create_github_release_job]
    steps:
      - name: Remove existing README.md
        run: rm -f README.md
      - name: Create new README.md
        run: |
          echo "Welcome to my CV repository!" > README.md
          echo "| Preview 1 | Preview 2 |" >> README.md
          echo "|:---:|:---:|" >> README.md
          echo "| ![Classic Theme Example of RenderCV](https://raw.githubusercontent.com/c2tz/cvv/main/cv_preview_0.png) | ![Sb2nov Theme Example of RenderCV](https://raw.githubusercontent.com/c2tz/cvv/main/cv_preview_1.png) |" >> README.md
          echo "" >> README.md  # Ajouter une ligne vide comme séparation
          echo "You can [download it](https://github.com/c2tz/cvv/releases/download/${{ env.NAME }}/Google_CV.pdf)." >> README.md
          echo "Test" >> README.md

  commit_readme_job:
    runs-on: ubuntu-latest
    needs: [update_readme_job]
    steps:
      - name: Commit README.md
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "docs(bot): updated README file with new content"

  push_changes_job:
    runs-on: ubuntu-latest
    needs: [commit_readme_job, create_github_release_job]
    steps:
      - name: Push Changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
